#!/bin/bash
# PokeWatch Kubernetes Commands Cheat Sheet

echo "=== PokeWatch Kubernetes Commands ==="
echo ""

echo "📦 DEPLOYMENT"
echo "  Deploy everything:         ./scripts/deploy_k8s.sh"
echo "  Build image:               eval \$(minikube docker-env) && docker build -t pokewatch-api:latest -f docker/api.Dockerfile ."
echo "  Apply manifests:           kubectl apply -f k8s/"
echo "  Delete deployment:         kubectl delete -f k8s/"
echo ""

echo "🔍 STATUS & MONITORING"
echo "  All resources:             kubectl get all -n pokewatch"
echo "  Pods status:               kubectl get pods -n pokewatch"
echo "  Pod details:               kubectl describe pod <pod-name> -n pokewatch"
echo "  Pod logs:                  kubectl logs <pod-name> -n pokewatch"
echo "  Follow logs:               kubectl logs -f <pod-name> -n pokewatch"
echo "  Service info:              kubectl get svc -n pokewatch"
echo "  HPA status:                kubectl get hpa -n pokewatch"
echo ""

echo "📈 SCALING"
echo "  Manual scale:              kubectl scale deployment/pokewatch-api --replicas=<N> -n pokewatch"
echo "  Enable auto-scaling:       kubectl apply -f k8s/hpa.yaml"
echo "  Disable auto-scaling:      kubectl delete hpa pokewatch-api-hpa -n pokewatch"
echo "  Watch HPA:                 kubectl get hpa -n pokewatch --watch"
echo ""

echo "🔄 ROLLING UPDATES"
echo "  Update image:              kubectl set image deployment/pokewatch-api api=pokewatch-api:<tag> -n pokewatch"
echo "  Rollout status:            kubectl rollout status deployment/pokewatch-api -n pokewatch"
echo "  Rollout history:           kubectl rollout history deployment/pokewatch-api -n pokewatch"
echo "  Rollback:                  kubectl rollout undo deployment/pokewatch-api -n pokewatch"
echo "  Restart pods:              kubectl rollout restart deployment/pokewatch-api -n pokewatch"
echo ""

echo "🌐 NETWORKING"
echo "  Port-forward:              kubectl port-forward -n pokewatch svc/pokewatch-api 8000:8000"
echo "  Minikube service:          minikube service pokewatch-api -n pokewatch"
echo "  Service URL:               minikube service pokewatch-api -n pokewatch --url"
echo ""

echo "🐛 DEBUGGING"
echo "  Exec into pod:             kubectl exec -it <pod-name> -n pokewatch -- /bin/bash"
echo "  Pod events:                kubectl get events -n pokewatch --sort-by='.lastTimestamp'"
echo "  Resource usage:            kubectl top pods -n pokewatch"
echo "  Describe deployment:       kubectl describe deployment pokewatch-api -n pokewatch"
echo ""

echo "⚙️ MINIKUBE"
echo "  Start cluster:             minikube start --driver=docker --memory=4096 --cpus=2"
echo "  Stop cluster:              minikube stop"
echo "  Delete cluster:            minikube delete"
echo "  Cluster status:            minikube status"
echo "  Dashboard:                 minikube dashboard"
echo "  Docker env:                eval \$(minikube docker-env)"
echo ""

echo "🧹 CLEANUP"
echo "  Delete namespace:          kubectl delete namespace pokewatch"
echo "  Delete all:                kubectl delete -f k8s/"
echo "  Stop Minikube:             minikube stop"
echo ""
